### ISSUE TITLE
[FR] Move/Edit Settings

### ISSUE THREAD

**Issue by SlRvb** [OfficerHalf/obsidian-auto-class#11]
I'd love the ability to move around the settings in an order that makes sense to me, something like this where you can grab the hamburger menu icon and rearrange it:

![Autoclass](https://user-images.githubusercontent.com/54087190/140629961-e4673dd8-8543-4842-bc0a-92e78ea2bc20.png)

---
Editing the classes or changing what folder by double clicking the area that I want to change would also be fantastic, I forget which classes I want to add to a folder and it'd be nice to not have to delete and redo it 😅.

---
(Bonus: Option to group them, something like Quickadd 👀)
![Obsidian_5RKfjoEvyc|100](https://user-images.githubusercontent.com/54087190/140630075-e2a93e13-935b-4dcd-98b3-1d8289cc1846.png)

**Comment by OfficerHalf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Edit existing paths/classes](https://trello.com/c/jIRhbaTp/7-edit-existing-paths-classes)

**Comment by OfficerHalf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Group settings](https://trello.com/c/Q7a144df/9-group-settings)

**Comment by OfficerHalf** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rearrange settings](https://trello.com/c/iinvDoqM/8-rearrange-settings)

**Comment by OfficerHalf** [comment]
Tracked in 3 separate cards on Trello. Editing existing ones is definitely planned, and I think you're right - QuickAdd is probably a good reference.

**Comment by OfficerHalf** [comment]
Revamped settings in v1.4.0, allowing for editing existing paths and re-ordering settings. #15

**Comment by OfficerHalf** [comment]
And groups added in #16, v1.5.0. I expect there's _PROBABLY_ some bugs in the group management logic, let me know if you see anything off.
