### ISSUE TITLE
[Bug] CSS Classes Only Applied To 1 Pane

### ISSUE THREAD

**Issue by SlRvb** [OfficerHalf/obsidian-auto-class#12]
The cssclasses seem to only be applied to 1 pane currently, it'd be nice if it applied to any panes that apply to the set cssclass if possible 🙏🏽 I always write with preview available and it'd be great if it applied to both. The only time when the panes are the same is when it bugs out and gets stuck on that styling.

Example of issue:
![roKW6Myp1L](https://user-images.githubusercontent.com/54087190/141172366-01c50153-216a-4dc4-ab44-569b77b3d2cf.gif)

**Comment by OfficerHalf** [comment]
Hmm this is one of the scenarios I made sure to try and support. Maybe I broke something in an update. Will investigate.

**Comment by OfficerHalf** [comment]
This specifically seems to be an issue with linked panes, which I definitely did not test (or know about at all, actually 😅. Should be able to support this, just need to figure out the right event to hook into.

**Comment by OfficerHalf** [comment]
@SlRvb fixed in #14, available in v1.3.0. Let me know if you see any more issues.
