### ISSUE TITLE
[Bug] Unable to Save Edits If in a Group

### ISSUE THREAD

**Issue by SlRvb** [OfficerHalf/obsidian-auto-class#17]
Rearranging folders into a group works pretty great, but adding classes or changing anything doesn't seem to save if it's in a group.

![Swbr2Ke0fc](https://user-images.githubusercontent.com/54087190/141688749-0594bbda-a5c5-4068-9728-60a459904a6d.gif)

**Comment by OfficerHalf** [comment]
Woops, good catch. Fixed in 1.5.2.
