### ISSUE TITLE
Tags in Frontmatter does not recognized

### ISSUE THREAD

**Issue by dariuszkowalski-com** [OfficerHalf/obsidian-auto-class#27]
When I put tag in a frontmatter section it is nor recognized and CSS file is not applied.

```
---
tags: 
  - #tag
---
```

doesn't work

`#tag`

 in body 

works

**Comment by OfficerHalf** [comment]
Looks like a regression with the latest obsidian versions. Good catch.

**Comment by OfficerHalf** [comment]
Fixed in v2.2.0.
