### ISSUE TITLE
Can Auto Class activate a CSS class in the presence of any YAML metadata? (Banners plugin use case).

### ISSUE THREAD

**Issue by DryIce1** [OfficerHalf/obsidian-auto-class#36]
Hi @OfficerHalf,

**use case / Problem**
- In v1 Obsidian using Inline Titles, the presence of a banner ([Banners Plugin](https://github.com/noatpad/obsidian-banners/)) usually covers the Inline Titles.
- Therefore notes with a banner should have a [Banners Inline Title CSS snippet](https://github.com/noatpad/obsidian-banners/issues/76) automatically applied to adjust the inline title down.
- However notes that have a banner don't universally share a unique file path or tag.
- Can the "Banner Inline Title" CSS snippet be activated automatically by the Auto Class plugin in the presence of only the banner yaml? e.g. `banner: "https://picsum.photos/500"`

thanks

**Comment by OfficerHalf** [comment]
@DryIce1 do you still think this would be useful? It seems like not that big a leap from just adding the CSS class to the YAML as well.

**Comment by DryIce1** [comment]
Thanks for the reply. My use case for the presence of a banner in the note has been solved using a css that includes `div.cm-editor:has(.has-banner) .inline-title`. 
So, no, it is not necessary for me anymore.
But thank you for your response.

**Comment by OfficerHalf** [comment]
Perfect, I think we can close this then. Sorry for the late reply, but glad you got it sorted.
