### ISSUE TITLE
Wildcard or Regex match

### ISSUE THREAD

**Issue by Rosefae** [OfficerHalf/obsidian-auto-class#37]
Would it be possible to add the ability to use wildcard characters or regex in the path to target a collection of paths rather than just a specific one? Maybe a toggle in the settings to use `string.match()` instead of `string.startsWith()` when comparing the path, or preprocessing the entered path to handle globbing with asterisks or something.

**Comment by OfficerHalf** [comment]
Released in v2.3.0.
